PUT https://localhost:5001/api/commands/53
Content-Type: application/json

{
  "howTo": "Make coffee"
}

###
PUT https://localhost:5001/api/commands/5
Content-Type: application/json

{
  "howTo": "Make coffee",
  "line": "Just doo it",
  "platform": "hahaha"
}

###
POST https://localhost:5001/api/commands
Content-Type: application/json

{
  "howTo": "How to test sjit",
  "line": "dotnet soep kip"
}

###
POST https://localhost:5001/api/commands
Content-Type: application/json

{
  "howTo": "How to test sjit",
  "line": "dotnet soep kip",
  "platform": "Home"
}

###
GET https://localhost:5001/api/commands/5
Accept: application/json

###
GET https://localhost:5001/api/commands
Accept: application/json